version: "3.8"

services:
  web:
    image: nginx:1.19.2-alpine
    volumes:
      - .:/var/www/html
      - ./docker/web/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - VIRTUAL_HOST=app-sample2.com

networks:
  default:
    external:
      name: nginx-proxy
